name: Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - next

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: "COMET Library: Clone translations"
        uses: actions/checkout@v4
        with:
          repository: vivid-planet/comet-lang
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "demo/admin/lang/comet-lang"

      - name: "COMET Brevo Library: Clone translations"
        uses: actions/checkout@v4
        with:
          repository: vivid-planet/comet-brevo-module-lang
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "demo/admin/lang/comet-brevo-module-lang"

      - name: "Demo: Clone translations"
        uses: actions/checkout@v4
        with:
          repository: vivid-planet/comet-brevo-module-demo-lang
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "demo/admin/lang/comet-brevo-module-demo-lang"

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

      - run: pnpm install --frozen-lockfile

      - name: Copy schema files
        run: pnpm run copy-schema-files

      - name: Build
        run: pnpm run build:lib

      - name: Lint
        run: |
          pnpm run lint
          # check for duplicate ids of formatted messages
          pnpm run intl:extract
          # check if schema files are up to date
          pnpm --filter '@comet/brevo-api' run generate-block-meta
          pnpm --filter '@comet/brevo-api' run generate-schema
          git diff --exit-code HEAD --
